version: '3.8'

services:
    webserver:
        image: nginx:latest
        container_name: webserver
        restart: always
        depends_on:
            - backend
        ports:
            - "8443:8443"
        volumes:
            - ./:/var/www
            - ./Dockerfiles/nginx:/etc/nginx/conf.d
            - /etc/letsencrypt:/etc/letsencrypt # Agregando este volumen para usar los certificados SSL/TLS
        networks:
            app-network:

    backend:
        restart: always
        depends_on:
            - database
        build:
            context: Dockerfiles/php
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./:/var/www
            - ./Dockerfiles/php/php.ini:/usr/local/etc/php/conf.d/local.ini

        networks:
            app-network:
networks:
    app-network:

volumes:
    app-data:
    oracle-data:
