version: '3.8'

services:
    database:
        env_file:
          - Dockerfiles/.env
        ports:
            - ${ORACLE_EXPOSE_PORT}:1521
networks:
    app-network:

volumes:
    app-data:
    oracle-data:
