version: '3.8'

services:
    webserver:
        image: nginx:latest
        container_name: webserver
        restart: always
        depends_on:
            - backend
        ports:
            - "8443:8443"
        volumes:
            - ./:/var/www
            - ./Dockerfiles/nginx:/etc/nginx/conf.d
            - /etc/letsencrypt:/etc/letsencrypt # Agregando este volumen para usar los certificados SSL/TLS
        networks:
            app-network:

    backend:
        restart: always
        depends_on:
            - database
        build:
            context: Dockerfiles/php
            dockerfile: Dockerfile
        container_name: backend
        network_mode: service:vpn-forti
        volumes:
            - ./:/var/www
            - ./Dockerfiles/php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./Dockerfiles/vpn/config:/etc/openconnect/config
        networks:
            app-network:
    database:
        restart: always
        container_name: oracle-db
        image: gvenzl/oracle-xe
        ports:
          - "1523:1521"
        environment:
          - ORACLE_PASSWORD=oracle123
          - ORACLE_DATABASE=portal
          - APP_USER=portalDba
          - APP_USER_PASSWORD=portalDba123
        volumes:
            - oracle-data:/opt/oracle/oradata
        networks:
            app-network:
    vpn-forti:
        restart: always
        privileged: true
        container_name: vpn-forti
        build:
            context: Dockerfiles/vpn
            dockerfile: Dockerfile
        tty: true
        command:
            - /bin/sh
            - -c
            - "openfortivpn -c /etc/openfortivpn/config"
        volumes:
            - ./Dockerfiles/vpn/config:/etc/openfortivpn/config
        networks:
            - app-network
networks:
    app-network:

volumes:
    app-data:
    oracle-data:
