version: '3.8'

services:
    webserver:
        image: nginx:latest
        container_name: webserver
        restart: always
        depends_on:
            - backend
        env_file:
            - .Dockerfiles/.env
        ports:
            - ${NGINX_HTTP_PORT}:80
        volumes:
            - ./:/var/www
            - ./Dockerfiles/nginx:/etc/nginx/conf.d
        networks:
            app-network:

    backend:
        restart: always
        depends_on:
            - database
        build:
            context: Dockerfiles/php
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./:/var/www
            - ./Dockerfiles/php/php.ini:/usr/local/etc/php/conf.d/local.ini

        networks:
            app-network:
    database:
        restart: always
        build:
            context: Dockerfiles/oracle
            dockerfile: Dockerfile
        container_name: oracle-db
        env_file:
            - .Dockerfiles/.env
        environment:
            ORACLE_PASSWORD: ${ORACLE_PASSWORD}
            ORACLE_ALLOW_REMOTE: true
            ORACLE_DISABLE_ASYNCH_IO: true
            ORACLE_ENABLE_XDB: true
        volumes:
            - oracle-data:/opt/oracle/oradata
        networks:
            app-network:
networks:
    app-network:

volumes:
    app-data:
    oracle-data:
