<?php

return [
    'base_url_api' => env('AUTENTICAR_BASE_URL') . env('AUTENTICAR_REALM') . '/',
    'realm' => env('AUTENTICAR_REALM', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'secret' => env('AUTENTICAR_SECRET', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'base_url' => env('AUTENTICAR_BASE_URL', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'client_id' => env('AUTENTICAR_CLIENT_ID', 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'grant_type' => env('AUTENTICAR_GRANT_TYPE', 'XXXXXXXXXXXXXXXXXXXXXXXXX'),
    'redirect_uri' => env('AUTENTICAR_REDIRECT_URI', 'XXXXXXXXXXXXXXXXXXXXX'),
];
