<?php

return [
    'client_id' => env('AUTENTICAR_CLIENT_ID', 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'grant_type' => env('AUTENTICAR_GRANT_TYPE', 'XXXXXXXXXXXXXXXXXXXXXXXXX'),

    'redirect_uri_afip' => env('AUTENTICAR_REDIRECT_URI_AFIP', 'XXXXXXXXXXXXXXXXXXXXX'),
    'base_url_afip' => env('AUTENTICAR_BASE_URL_AFIP', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'secret_afip' => env('AUTENTICAR_SECRET_AFIP', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'base_url_api_afip' => env('AUTENTICAR_BASE_URL_AFIP') . env('AUTENTICAR_REALM_AFIP') . '/',
    'realm_afip' => env('AUTENTICAR_REALM_AFIP', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),

    'redirect_uri_miargentina' => env('AUTENTICAR_REDIRECT_URI_MIARGENTINA', 'XXXXXXXXXXXXXXXXXXXXX'),
    'base_url_miargentina' => env('AUTENTICAR_BASE_URL_MIARGENTINA', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'secret_miargentina' => env('AUTENTICAR_SECRET_MIARGENTINA', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'base_url_api_miargentina' => env('AUTENTICAR_BASE_URL_MIARGENTINA') . env('AUTENTICAR_REALM_MIARGENTINA') . '/',
    'realm_miargentina' => env('AUTENTICAR_REALM_MIARGENTINA', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),

    'redirect_uri_anses' => env('AUTENTICAR_REDIRECT_URI_ANSES', 'XXXXXXXXXXXXXXXXXXXXX'),
    'base_url_anses' => env('AUTENTICAR_BASE_URL_ANSES', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'secret_anses' => env('AUTENTICAR_SECRET_ANSES', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'base_url_api_anses' => env('AUTENTICAR_BASE_URL_ANSES') . env('AUTENTICAR_REALM_ANSES') . '/',
    'realm_anses' => env('AUTENTICAR_REALM_ANSES', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),

    'redirect_uri_renaper' => env('AUTENTICAR_REDIRECT_URI_RENAPER', 'XXXXXXXXXXXXXXXXXXXXX'),
    'base_url_renaper' => env('AUTENTICAR_BASE_URL_RENAPER', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'secret_renaper' => env('AUTENTICAR_SECRET_RENAPER', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
    'base_url_api_renaper' => env('AUTENTICAR_BASE_URL_RENAPER') . env('AUTENTICAR_REALM_RENAPER') . '/',
    'realm_renaper' => env('AUTENTICAR_REALM_RENAPER', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),

];